package conf

var (
	// 文档title与图片对应关系
	TITLE_TO_IMG = map[string]string{
		"生命值": "Health Meter.png",
		"饥饿值": "Hunger Meter.png",
		"理智值": "Sanity Meter.png",
	}
	// 角色
	HERO_IMG_MAP = map[string]string{
		"WX-78 Filter.png":        "WX-78",
		"Maxwell Filter.png":      "麦斯威尔",
		"Wickerbottom Filter.png": "薇克巴顿",
		"Woodie Filter.png":       "伍迪",
		"Wolfgang Filter.png":     "沃尔夫冈",
		"Warly Filter.png":        "沃利",
		"Wanda Filter.png":        "旺达",
		"Wes Filter.png":          "韦斯",
		"Wormwood Filter.png":     "沃姆伍德",
		"Wigfrid Filter.png":      "薇格弗德",
		"Webber Filter.png":       "韦伯",
		"Walter Filter.png":       "沃尔特",
		"Wendy Filter.png":        "温蒂",
		"Winona Filter.png":       "薇诺娜",
		"Willow Filter.png":       "薇洛",
		"Wurt Filter.png":         "沃特",
		"Wilson Filter.png":       "威尔逊",
	}

	// 联机物品类别
	TYPE_IMG_MAP = map[string]string{
		"Healing Filter.png":                       "治疗",
		"Ancient Pseudoscience Station Filter.png": "远古",
		"Food & Gardening Filter.png":              "食物",
		"Food Gardening Filter.png":                "食物",
		"Bottle Exchange Station Filter.png":       "瓶罐交易",
		"Summer Items Filter.png":                  "雨具",
		"Decorations Filter.png":                   "装饰",
		"Clothing Filter.png":                      "服装",
		"Winter Items Filter.png":                  "冬季物品",
		"Shadow Magic Filter.png":                  "魔法",
		"Cartography Station Filter.png":           "制图",
		"Brightsmithy Filter.png":                  "辉煌铁匠铺",
		"Weapons Filter.png":                       "武器",
		"Celestial Station Filter.png":             "天体",
		"Refined Materials Filter.png":             "精炼材料",
		"Shadowcrafting Filter.png":                "暗影术",
		"Armour Filter.png":                        "盔甲",
		"Fishing Filter.png":                       "钓鱼",
		"Tools Filter.png":                         "工具",
		"Seafaring Filter.png":                     "航行",
		"Seasonings Station Filter.png":            "香料",
		"Cooking Filter.png":                       "烹饪",
		"Storage Solutions Filter.png":             "储物方案",
		"Light Sources Filter.png":                 "光源",
		"Structures Filter.png":                    "建筑",
	}

	// 物品合成
	ITEM_FORMALU = map[string]string{
		"Super-Processing Circuit.png":   "超级处理器电路",
		"Gardeneer Hat.png":              "耕作先驱帽",
		"Guardian's Horn.png":            "守护者之角",
		"Spider Gland.png":               "蜘蛛腺",
		"Lux Aeterna.png":                "永恒之光",
		"Deerclops Eyeball.png":          "独眼巨鹿眼球",
		"Thulecite.png":                  "铥矿",
		"Papyrus.png":                    "莎草纸",
		"Gastrogain Circuit.png":         "胃增益电路",
		"Acceleration Circuit.png":       "加速电路",
		"Pile of Balloons.png":           "一堆气球",
		"Horticulture, Abridged.png":     "园艺学简编版",
		"Thick Fur.png":                  "熊皮",
		"Boards.png":                     "木板",
		"Thermal Stone.png":              "暖石",
		"Light Bulb.png":                 "荧光果",
		"Bucket-o-poop.png":              "便便桶",
		"Green Cap.png":                  "采摘的绿蘑菇",
		"Don't Starve Together icon.png": "饥荒：联机版",
		"Seeds.png":                      "种子",
		"Time Pieces.png":                "时间碎片",
		"Red Gem.png":                    "红宝石",
		"Water Balloon.png":              "水球",
		"Electrical Doodad.png":          "电子元件",
		"Ice.png":                        "冰",
		"Glommer's Goop.png":             "格罗姆的黏液",
		"Azure Feather.png":              "蓝色羽毛",
		"Scales.png":                     "鳞片",
		"Enlightened Shard.png":          "启迪碎片",
		"Rocks.png":                      "石头",
		"Captain's Tricorn.png":          "船长的三角帽",
		"Infused Moon Shard.png":         "注能月亮碎片",
		"Feather Pencil.png":             "羽毛笔",
		"Slurper Pelt.png":               "啜食者皮",
		"Cratered Moonrock.png":          "带孔月岩",
		"Nitre.png":                      "硝石",
		"Cookie Cutter Shell.png":        "饼干切割机壳",
		"Crimson_Feather.png":            "红色羽毛",
		"Dark Petals.png":                "深色花瓣",
		"Brightshade Husk.png":           "亮茄外壳",
		"Canary (Volatile).png":          "金丝雀（中毒）",
		"Hound%27s_Tooth.png":            "犬牙",
		"Fig.png":                        "无花果",
		"Green Gem.png":                  "绿宝石",
		"Health Meter.png":               "生命值",
		"Cut_Reeds.png":                  "芦苇",
		"Carrot.png":                     "胡萝卜",
		"Clockmaker's Tools.png":         "钟表匠工具",
		"Backtrek Watch.png":             "溯源表",
		"Dreadstone.png":                 "绝望石",
		"Manure.png":                     "粪肥",
		"Down Feather.png":               "麋鹿鹅羽毛",
		"Pepper.png":                     "辣椒",
		"Shroom Skin.png":                "蘑菇皮",
		"Koalefant Trunk.png":            "象鼻",
		"Broken Shell (DST).png":         "壳碎片",
		"Stinger.png":                    "蜂刺",
		"Freshwater Fish.png":            "淡水鱼",
		"Saffron Feather.png":            "黄色羽毛",
		"Pickaxe.png":                    "鹤嘴锄",
		"Fur Tuft.png":                   "毛丛",
		"Cut Stone.png":                  "石砖",
		"Purple Gem.png":                 "紫宝石",
		"Living_Log.png":                 "活木",
		"Cut Reeds.png":                  "采下的芦苇",
		"Cactus Flower.png":              "仙人掌花",
		"Yellow Gem.png":                 "黄宝石",
		"Cat Tail.png":                   "猫尾",
		"Cut Grass.png":                  "采下的草",
		"Twigs.png":                      "树枝",
		"Silk.png":                       "蜘蛛丝",
		"Sanity Meter.png":               "理智值",
		"Leafy Meat.png":                 "叶肉",
		"Sewing Kit.png":                 "针线包",
		"Rotten Egg.png":                 "腐烂鸟蛋",
		"Bee.png":                        "蜜蜂",
		"The End is Nigh.png":            "末日将至",
		"Moon Rock.png":                  "月岩",
		"Jet_Feather.png":                "黑色羽毛",
		"Processing Circuit.png":         "#处理器电路",
		"Pine Cone.png":                  "松果",
		"Empty Bottle DST.png":           "空瓶子",
		"Straw Hat.png":                  "草帽",
		"Red_Gem.png":                    "红宝石",
		"Pig Skin.png":                   "猪皮",
		"Monster Meat.png":               "怪物肉",
		"Berry Bush.png":                 "浆果丛",
		"Pure Horror.png":                "纯粹恐惧",
		"Spittlefish.png":                "口水鱼",
		"Blue Cap.png":                   "采摘的蓝蘑菇",
		"Mandrake.png":                   "曼德拉草",
		"Log.png":                        "木头",
		"Luxury Axe.png":                 "黄金斧头",
		"Malbatross Feather.png":         "邪天翁羽毛",
		"Petals.png":                     "花瓣",
		"Rot.png":                        "腐烂物",
		"Moon Moth Wings.png":            "月蛾翅膀",
		"Gold Nugget.png":                "金块",
		"Straw Roll.png":                 "草席卷",
		"Gnarwail Horn.png":              "一角鲸的角",
		"Walking Cane.png":               "步行手杖",
		"Potato.png":                     "土豆",
		"Batilisk_Wing.png":              "蝙蝠翅膀",
		"Living Log.png":                 "活木头",
		"Tentacle Spots.png":             "触手皮",
		"Spark Ark Full.png":             "火花柜",
		"Azure_Feather.png":              "蓝色羽毛",
		"Walter Portrait.png":            "沃尔特",
		"Pumpkin.png":                    "南瓜",
		"Glow Berry.png":                 "发光浆果",
		"Ashes.png":                      "灰烬",
		"Bio Data.png":                   "生物数据",
		"Opulent Pickaxe.png":            "黄金鹤嘴锄",
		"Fireflies.png":                  "萤火虫",
		"Orange Gem.png":                 "橙宝石",
		"Red Cap.png":                    "采摘的红蘑菇",
		"Beefalo Wool.png":               "牛毛",
		"Volt Goat Horn.png":             "伏特羊角",
		"Hardy Circuit.png":              "#强化电路",
		"Walrus Tusk.png":                "海象牙",
		"Beefalo Horn.png":               "牛角",
		"Fashion Goggles.png":            "时髦的护目镜",
		"Spear.png":                      "长矛",
		"Black Flag.png":                 "黑旗",
		"Marble.png":                     "大理石",
		"Tillweed.png":                   "犁地草",
		"Compost Wrap.png":               "肥料包",
		"Thulecite Medallion.png":        "铥矿徽章",
		"Frazzled Wires.png":             "玩具#烂电线",
		"Gears.png":                      "齿轮",
		"Flare.png":                      "信号弹",
		"Baritone Shell Bell 3.png":      "贝壳钟",
		"Lune Tree Blossom.png":          "月树花",
		"Winter Koalefant Trunk.png":     "冬象鼻",
		"Scrap.png":                      "废铁",
		"Kelp Fronds.png":                "海带叶",
		"Hound's Tooth.png":              "犬牙",
		"Telltale Heart.png":             "告密的心",
		"Nightmare Fuel.png":             "噩梦燃料",
		"Royal Jelly.png":                "蜂王浆",
		"Honeycomb.png":                  "蜜脾",
		"Wax Paper.png":                  "蜡纸",
		"Steel Wool.png":                 "钢丝绵",
		"Purple_Gem.png":                 "紫宝石",
		"Moon Shard.png":                 "月亮碎片",
		"Honey.png":                      "蜂蜜",
		"Dapper Vest.png":                "犬牙背心",
		"Top Hat.png":                    "高礼帽",
		"Wormwood_Portrait.png":          "沃姆伍德",
		"Palmcone Scale.png":             "棕榈松果树鳞片",
		"Desert Stone.png":               "沙之石",
		"Beeswax.png":                    "蜂蜡",
		"link={{{2}}}":                   "link={{{2}}}",
		"Beard Hair.png":                 "胡须",
		"Moleworm Item.png":              "鼹鼠",
		"Driftwood Piece.png":            "浮木桩",
		"Wooden Ball Bobber.png":         "木球浮标",
		"Saffron_Feather.png":            "黄色羽毛",
		"Rabbit.png":                     "兔子",
		"Nightmare_Fuel.png":             "噩梦燃料",
		"Meat.png":                       "肉",
		"Mosquito Sack.png":              "蚊子血囊",
		"Iridescent Gem.png":             "彩虹宝石",
		"Dark Tatters DST.png":           "暗影碎布",
		"Salt Crystals.png":              "盐晶",
		"Bone Shards.png":                "骨头碎片",
		"Crimson Feather.png":            "红色羽毛",
		"Log Suit.png":                   "木甲",
		"Gunpowder.png":                  "火药",
		"Feathery Canvas.png":            "羽毛帆布",
		"Life Giving Amulet.png":         "重生护符",
		"Toma Root.png":                  "番茄",
		"Blue Gem.png":                   "蓝宝石",
		"Jet Feather.png":                "黑色羽毛",
		"Malbatross Bill.png":            "邪天翁喙",
		"Don't Starve icon.png":          "饥荒",
		"Charcoal.png":                   "木炭",
		"Electric Milk.png":              "带电的羊奶",
		"Watermelon.png":                 "西瓜",
		"Egg.png":                        "鸟蛋",
		"Rope.png":                       "绳子",
		"Batilisk Wing.png":              "洞穴蝙蝠翅膀",
		"Thulecite Fragments.png":        "铥矿碎片",
		"Mourning Glory.png":             "哀悼荣耀",
		"Garlic.png":                     "大蒜",
		"Moleworm.png":                   "鼹鼠",
		"Bunny Puff.png":                 "兔绒",
		"Pure Brilliance.png":            "纯粹辉煌",
		"Flint.png":                      "燧石",
	}

	// 单机分类
	TYPE_IMG_MAP_SINGLE = map[string]string{
		"Icon Survival.png":    "生存栏",
		"Icon Magic.png":       "魔法栏",
		"Icon Dress.png":       "衣物栏",
		"Icon Fight.png":       "战斗栏",
		"Icon Ancient.png":     "远古栏",
		"Icon Tools.png":       "工具栏",
		"Icon Science.png":     "科学栏",
		"Icon Refine.png":      "精炼栏",
		"Icon Green Thumb.png": "园艺栏",
		"Icon Light.png":       "照明栏",
		"Icon Food.png":        "食物栏",
		"Icon Structures.png":  "建筑栏",
	}

	// 单机分类错误使用联机分类
	TYPE_SINGLE_TO_OLINE = map[string]string{
		"Tools Filter.png":         "Icon Tools.png",
		"Light Sources Filter.png": "Icon Light.png",
		"Structures Filter.png":    "Icon Structures.png",
	}

	// 解锁
	JIE_SUO = map[string]string{
		"Warly Portrait.png":     "沃利",
		"Wigfrid Portrait.png":   "薇格弗德",
		"Think Tank.png":         "智囊团",
		"Science Machine.png":    "科学机器",
		"Alchemy Engine.png":     "炼金引擎",
		"Prestihatitator.png":    "灵子分解器",
		"Bookcase.png":           "书柜",
		"Don't Starve icon.png":  "饥荒",
		"Blueprint (rare).png":   "蓝图#稀有蓝图",
		"Shadow Manipulator.png": "暗影操控器",
		"Bio Scanalyzer.png":     "生物分析扫描仪",
	}

	// 总map
	TOTLE = map[string]string{
		// 角色
		"WX-78 Filter.png":        "WX-78",
		"Maxwell Filter.png":      "麦斯威尔",
		"Wickerbottom Filter.png": "薇克巴顿",
		"Woodie Filter.png":       "伍迪",
		"Wolfgang Filter.png":     "沃尔夫冈",
		"Warly Filter.png":        "沃利",
		"Wanda Filter.png":        "旺达",
		"Wes Filter.png":          "韦斯",
		"Wormwood Filter.png":     "沃姆伍德",
		"Wigfrid Filter.png":      "薇格弗德",
		"Webber Filter.png":       "韦伯",
		"Walter Filter.png":       "沃尔特",
		"Wendy Filter.png":        "温蒂",
		"Winona Filter.png":       "薇诺娜",
		"Willow Filter.png":       "薇洛",
		"Wurt Filter.png":         "沃特",
		"Wilson Filter.png":       "威尔逊",

		// 联机分类
		"Healing Filter.png":                       "治疗",
		"Ancient Pseudoscience Station Filter.png": "远古",
		"Food & Gardening Filter.png":              "食物",
		"Food Gardening Filter.png":                "食物",
		"Bottle Exchange Station Filter.png":       "瓶罐交易",
		"Summer Items Filter.png":                  "雨具",
		"Decorations Filter.png":                   "装饰",
		"Clothing Filter.png":                      "服装",
		"Winter Items Filter.png":                  "冬季物品",
		"Shadow Magic Filter.png":                  "魔法",
		"Cartography Station Filter.png":           "制图",
		"Brightsmithy Filter.png":                  "辉煌铁匠铺",
		"Weapons Filter.png":                       "武器",
		"Celestial Station Filter.png":             "天体",
		"Refined Materials Filter.png":             "精炼材料",
		"Shadowcrafting Filter.png":                "暗影术",
		"Armour Filter.png":                        "盔甲",
		"Fishing Filter.png":                       "钓鱼",
		"Tools Filter.png":                         "工具",
		"Seafaring Filter.png":                     "航行",
		"Seasonings Station Filter.png":            "香料",
		"Cooking Filter.png":                       "烹饪",
		"Storage Solutions Filter.png":             "储物方案",
		"Light Sources Filter.png":                 "光源",
		"Structures Filter.png":                    "建筑",
		"Rain Gear Filter.png":                     "雨具",
		"Beefalo Riding Filter.png":                "骑乘皮弗娄牛",

		// 单机分类
		"Icon Survival.png":    "生存栏",
		"Icon Magic.png":       "魔法栏",
		"Icon Dress.png":       "衣物栏",
		"Icon Fight.png":       "战斗栏",
		"Icon Ancient.png":     "远古栏",
		"Icon Tools.png":       "工具栏",
		"Icon Science.png":     "科学栏",
		"Icon Refine.png":      "精炼栏",
		"Icon Green Thumb.png": "园艺栏",
		"Icon Light.png":       "照明栏",
		"Icon Food.png":        "食物栏",
		"Icon Structures.png":  "建筑栏",

		// 解锁
		"Warly Portrait.png":     "沃利",
		"Wigfrid Portrait.png":   "薇格弗德",
		"Think Tank.png":         "智囊团",
		"Science Machine.png":    "科学机器",
		"Alchemy Engine.png":     "炼金引擎",
		"Prestihatitator.png":    "灵子分解器",
		"Bookcase.png":           "书柜",
		"Don't Starve icon.png":  "饥荒",
		"Blueprint (rare).png":   "蓝图#稀有蓝图",
		"Shadow Manipulator.png": "暗影操控器",
		"Bio Scanalyzer.png":     "生物分析扫描仪",

		// 合成表
		"Super-Processing Circuit.png":   "超级处理器电路",
		"Gardeneer Hat.png":              "耕作先驱帽",
		"Guardian's Horn.png":            "守护者之角",
		"Spider Gland.png":               "蜘蛛腺",
		"Lux Aeterna.png":                "永恒之光",
		"Deerclops Eyeball.png":          "独眼巨鹿眼球",
		"Thulecite.png":                  "铥矿",
		"Papyrus.png":                    "莎草纸",
		"Gastrogain Circuit.png":         "胃增益电路",
		"Acceleration Circuit.png":       "加速电路",
		"Pile of Balloons.png":           "一堆气球",
		"Horticulture, Abridged.png":     "园艺学简编版",
		"Thick Fur.png":                  "熊皮",
		"Boards.png":                     "木板",
		"Thermal Stone.png":              "暖石",
		"Light Bulb.png":                 "荧光果",
		"Bucket-o-poop.png":              "便便桶",
		"Green Cap.png":                  "采摘的绿蘑菇",
		"Don't Starve Together icon.png": "饥荒：联机版",
		"Seeds.png":                      "种子",
		"Time Pieces.png":                "时间碎片",
		"Red Gem.png":                    "红宝石",
		"Water Balloon.png":              "水球",
		"Electrical Doodad.png":          "电子元件",
		"Ice.png":                        "冰",
		"Glommer's Goop.png":             "格罗姆的黏液",
		"Azure Feather.png":              "蓝色羽毛",
		"Scales.png":                     "鳞片",
		"Enlightened Shard.png":          "启迪碎片",
		"Rocks.png":                      "石头",
		"Captain's Tricorn.png":          "船长的三角帽",
		"Infused Moon Shard.png":         "注能月亮碎片",
		"Feather Pencil.png":             "羽毛笔",
		"Slurper Pelt.png":               "啜食者皮",
		"Cratered Moonrock.png":          "带孔月岩",
		"Nitre.png":                      "硝石",
		"Cookie Cutter Shell.png":        "饼干切割机壳",
		"Crimson_Feather.png":            "红色羽毛",
		"Dark Petals.png":                "深色花瓣",
		"Brightshade Husk.png":           "亮茄外壳",
		"Canary (Volatile).png":          "金丝雀（中毒）",
		"Hound%27s_Tooth.png":            "犬牙",
		"Fig.png":                        "无花果",
		"Green Gem.png":                  "绿宝石",
		"Health Meter.png":               "生命值",
		"Cut_Reeds.png":                  "芦苇",
		"Carrot.png":                     "胡萝卜",
		"Clockmaker's Tools.png":         "钟表匠工具",
		"Backtrek Watch.png":             "溯源表",
		"Dreadstone.png":                 "绝望石",
		"Manure.png":                     "粪肥",
		"Down Feather.png":               "麋鹿鹅羽毛",
		"Pepper.png":                     "辣椒",
		"Shroom Skin.png":                "蘑菇皮",
		"Koalefant Trunk.png":            "象鼻",
		"Broken Shell (DST).png":         "壳碎片",
		"Stinger.png":                    "蜂刺",
		"Freshwater Fish.png":            "淡水鱼",
		"Saffron Feather.png":            "黄色羽毛",
		"Pickaxe.png":                    "鹤嘴锄",
		"Fur Tuft.png":                   "毛丛",
		"Cut Stone.png":                  "石砖",
		"Purple Gem.png":                 "紫宝石",
		"Living_Log.png":                 "活木",
		"Cut Reeds.png":                  "采下的芦苇",
		"Cactus Flower.png":              "仙人掌花",
		"Yellow Gem.png":                 "黄宝石",
		"Cat Tail.png":                   "猫尾",
		"Cut Grass.png":                  "采下的草",
		"Twigs.png":                      "树枝",
		"Silk.png":                       "蜘蛛丝",
		"Sanity Meter.png":               "理智值",
		"Leafy Meat.png":                 "叶肉",
		"Sewing Kit.png":                 "针线包",
		"Rotten Egg.png":                 "腐烂鸟蛋",
		"Bee.png":                        "蜜蜂",
		"The End is Nigh.png":            "末日将至",
		"Moon Rock.png":                  "月岩",
		"Jet_Feather.png":                "黑色羽毛",
		"Processing Circuit.png":         "#处理器电路",
		"Pine Cone.png":                  "松果",
		"Empty Bottle DST.png":           "空瓶子",
		"Straw Hat.png":                  "草帽",
		"Red_Gem.png":                    "红宝石",
		"Pig Skin.png":                   "猪皮",
		"Monster Meat.png":               "怪物肉",
		"Berry Bush.png":                 "浆果丛",
		"Pure Horror.png":                "纯粹恐惧",
		"Spittlefish.png":                "口水鱼",
		"Blue Cap.png":                   "采摘的蓝蘑菇",
		"Mandrake.png":                   "曼德拉草",
		"Log.png":                        "木头",
		"Luxury Axe.png":                 "黄金斧头",
		"Malbatross Feather.png":         "邪天翁羽毛",
		"Petals.png":                     "花瓣",
		"Rot.png":                        "腐烂物",
		"Moon Moth Wings.png":            "月蛾翅膀",
		"Gold Nugget.png":                "金块",
		"Straw Roll.png":                 "草席卷",
		"Gnarwail Horn.png":              "一角鲸的角",
		"Walking Cane.png":               "步行手杖",
		"Potato.png":                     "土豆",
		"Batilisk_Wing.png":              "蝙蝠翅膀",
		"Living Log.png":                 "活木头",
		"Tentacle Spots.png":             "触手皮",
		"Spark Ark Full.png":             "火花柜",
		"Azure_Feather.png":              "蓝色羽毛",
		"Walter Portrait.png":            "沃尔特",
		"Pumpkin.png":                    "南瓜",
		"Glow Berry.png":                 "发光浆果",
		"Ashes.png":                      "灰烬",
		"Bio Data.png":                   "生物数据",
		"Opulent Pickaxe.png":            "黄金鹤嘴锄",
		"Fireflies.png":                  "萤火虫",
		"Orange Gem.png":                 "橙宝石",
		"Red Cap.png":                    "采摘的红蘑菇",
		"Beefalo Wool.png":               "牛毛",
		"Volt Goat Horn.png":             "伏特羊角",
		"Hardy Circuit.png":              "#强化电路",
		"Walrus Tusk.png":                "海象牙",
		"Beefalo Horn.png":               "牛角",
		"Fashion Goggles.png":            "时髦的护目镜",
		"Spear.png":                      "长矛",
		"Black Flag.png":                 "黑旗",
		"Marble.png":                     "大理石",
		"Tillweed.png":                   "犁地草",
		"Compost Wrap.png":               "肥料包",
		"Thulecite Medallion.png":        "铥矿徽章",
		"Frazzled Wires.png":             "玩具#烂电线",
		"Gears.png":                      "齿轮",
		"Flare.png":                      "信号弹",
		"Baritone Shell Bell 3.png":      "贝壳钟",
		"Lune Tree Blossom.png":          "月树花",
		"Winter Koalefant Trunk.png":     "冬象鼻",
		"Scrap.png":                      "废铁",
		"Kelp Fronds.png":                "海带叶",
		"Hound's Tooth.png":              "犬牙",
		"Telltale Heart.png":             "告密的心",
		"Nightmare Fuel.png":             "噩梦燃料",
		"Royal Jelly.png":                "蜂王浆",
		"Honeycomb.png":                  "蜜脾",
		"Wax Paper.png":                  "蜡纸",
		"Steel Wool.png":                 "钢丝绵",
		"Purple_Gem.png":                 "紫宝石",
		"Moon Shard.png":                 "月亮碎片",
		"Honey.png":                      "蜂蜜",
		"Dapper Vest.png":                "犬牙背心",
		"Top Hat.png":                    "高礼帽",
		"Wormwood_Portrait.png":          "沃姆伍德",
		"Palmcone Scale.png":             "棕榈松果树鳞片",
		"Desert Stone.png":               "沙之石",
		"Beeswax.png":                    "蜂蜡",
		"link={{{2}}}":                   "link={{{2}}}",
		"Beard Hair.png":                 "胡须",
		"Moleworm Item.png":              "鼹鼠",
		"Driftwood Piece.png":            "浮木桩",
		"Wooden Ball Bobber.png":         "木球浮标",
		"Saffron_Feather.png":            "黄色羽毛",
		"Rabbit.png":                     "兔子",
		"Nightmare_Fuel.png":             "噩梦燃料",
		"Meat.png":                       "肉",
		"Mosquito Sack.png":              "蚊子血囊",
		"Iridescent Gem.png":             "彩虹宝石",
		"Dark Tatters DST.png":           "暗影碎布",
		"Salt Crystals.png":              "盐晶",
		"Bone Shards.png":                "骨头碎片",
		"Crimson Feather.png":            "红色羽毛",
		"Log Suit.png":                   "木甲",
		"Gunpowder.png":                  "火药",
		"Feathery Canvas.png":            "羽毛帆布",
		"Life Giving Amulet.png":         "重生护符",
		"Toma Root.png":                  "番茄",
		"Blue Gem.png":                   "蓝宝石",
		"Jet Feather.png":                "黑色羽毛",
		"Malbatross Bill.png":            "邪天翁喙",
		"Charcoal.png":                   "木炭",
		"Electric Milk.png":              "带电的羊奶",
		"Watermelon.png":                 "西瓜",
		"Egg.png":                        "鸟蛋",
		"Rope.png":                       "绳子",
		"Batilisk Wing.png":              "洞穴蝙蝠翅膀",
		"Thulecite Fragments.png":        "铥矿碎片",
		"Mourning Glory.png":             "哀悼荣耀",
		"Garlic.png":                     "大蒜",
		"Moleworm.png":                   "鼹鼠",
		"Bunny Puff.png":                 "兔绒",
		"Pure Brilliance.png":            "纯粹辉煌",
		"Flint.png":                      "燧石",
		"Flowers1.png":                   "花",
		"Retinazor Phase 1.png":          "双子魔眼",
		"Spider.png":                     "蜘蛛",
		"Spider Queen.png":               "蜘蛛女王",
		"Cookie Cutter.png":              "饼干切割机",
		"Broken Clockworks1.png":         "损坏的发条装置",
		"Trap.png":                       "陷阱",
		"Evil Flowers1.png":              "恶魔之花",
		"Sapling.png":                    "树苗",
		"Spider Den.png":                 "蜘蛛窝",
		"Ornate Chest.png":               "华丽箱子",
		"Crustashine.png":                "发光蟹",
	}

	// 错误的掉落信息
	DIAO_LUO_ERR = map[string]string{
		"地震":                             "",
		"文件:文件:Stalagmite.png":           "",
		"粗壮常青树（页面不存在）":                   "",
		"文件:Palace.png":                  "",
		"文件:Cactus.png":                  "",
		"文件:A Smashing Pot.png":          "",
		"文件:Oasis Cactus.png":            "",
		"文件:Vitreoasis.png":              "",
		"文件:Broken Clockworks.png":       "",
		"文件:Prime Ape Hut.png":           "",
		"文件:Flotsam.png":                 "",
		"文件:Secret Bandit Camp.png":      "",
		"文件:Suspicious Moonrocks.png":    "",
		"桦栗果精":                           "",
		"文件:Splumonkey Pod.png":          "",
		"文件:Slot Machine.png":            "",
		"文件:Seaworthy Build.png":         "",
		"Ancient Moon Statue.png（页面不存在）": "",
		"文件:Bones.png":                   "",
		"文件:Lava Pool.png":               "",
		"文件:Dragoon Egg.png":             "",
		"文件:Rabid Beetle.png":            "",
		"芦苇（页面不存在）":                      "",
		"威尔逊":                            "",
		"常青树（页面不存在）":                     "",
		"文件:Watery Grave.png":            "",
		"文件:Rock Moon.png":               "",
		"文件:Chest of the Depths.png":     "",
		"文件:文件:Hot Spring Glassed.png":   "",
		"文件:Small Vitreoasis.png":        "",
		"海洋":                             "",
		"恐怖之眼":                           "Eye of Terror Phase 2.png",
		"文件:Grave.png":                   "",
		"文件:Steamer Trunk.png":           "",
		"文件:Sea Bones.png":               "",
		"文件:Wicker Basket.png":           "",
		"文件:Moon Glass 1.png":            "",
		"文件:Barren Berry Bush.png":       "",
		"文件:Glowfly Cocoon.png":          "",
		"文件:Charged Glassy Rock.png":     "",
		"独眼巨鹿":                           "",
		"文件:Hound Mound.png":             "",
		"文件:Stalagmite Tall.png":         "",
		"文件:Totally Normal Tree.png":     "",
		"猴尾草":                            "",
		"桦栗树（页面不存在）":                     "",
		"文件:StalagmiteTall.png":          "",
		"文件:Sunken Boat.png":             "",
		"文件:Sandy Pile.png":              "",
		"文件:Sunken Chest.png":            "",
		"文件:Slotmachine.png":             "",
		"文件:Broken Machinery.png":        "",
		"冬季盛宴":                           "",
		"赃物袋":                            "Loot Stash.png",
		"暗影秘典":                           "",
		"文件:.png":                        "",
	}
)
